id = "pytest-lsp"
name = "pytest Language Server"
version = "0.3.0"
schema_version = 1
authors = ["Thiago Bellini Ribeiro <hackedbellini@gmail.com>"]
description = "A blazingly fast Language Server Protocol implementation for pytest"
repository = "https://github.com/bellini666/pytest-language-server"

[language_servers.pytest-lsp]
name = "pytest Language Server"
languages = ["Python"]
